/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.trojasviejas.component.main;

import com.trojasviejas.component.login.MessageErrorDialog;
import com.trojasviejas.demo.form.FrmReport;
import com.trojasviejas.models.utility.ReportCardModel;
import javax.swing.Icon;
import javax.swing.JFrame;

/**
 *
 * @author Willian
 */
public class ReportsCard extends javax.swing.JPanel {

    /**
     * Creates new form ReportsCard
     */
    public ReportsCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMonth = new com.trojasviejas.swing.fields.LinearTextField();
        txtYear = new com.trojasviejas.swing.fields.LinearTextField();
        jLabel1 = new javax.swing.JLabel();
        panelShadow1 = new com.trojasviejas.swing.panels.PanelShadow();
        lblReportCardHeader = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        btnRInvoice = new com.trojasviejas.swing.buttons.Button();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 152, 224), 1, true));

        txtMonth.setLabelText("Mes");

        txtYear.setLabelText("Año");
        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtYearKeyTyped(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblReportCardHeader.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblReportCardHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportCardHeader.setText("ENCABEZADO");

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReportCardHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblReportCardHeader)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lblIcon.setBackground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));
        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imagen.png"))); // NOI18N
        lblIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnRInvoice.setBackground(new java.awt.Color(27, 152, 224));
        btnRInvoice.setForeground(new java.awt.Color(255, 255, 255));
        btnRInvoice.setText("Generar reporte");
        btnRInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMonth, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(txtYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnRInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)))
                        .addComponent(btnRInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
    }// </editor-fold>//GEN-END:initComponents

   
    private String month;
    private int year;
    public FrmReport currentReportWindow;  
    public int indexReport = 0;
     
    MessageErrorDialog errorMessage = new MessageErrorDialog(new JFrame());
    
    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    private void btnRInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRInvoiceActionPerformed

        switch (indexReport) {
            case 1 -> currentReportWindow.generateReport(indexReport, month, year);
            case 2 -> currentReportWindow.generateReport(indexReport, month, year);
            case 3 -> verifyDataForInvoice(); 
            case 4 -> verifyDataForRegister();
            default ->{}
        }
    }//GEN-LAST:event_btnRInvoiceActionPerformed

    private void verifyDataForInvoice(){
        verifyYear();
    }
        private void verifyDataForRegister(){
            verifyMonth();
            verifyYear();
    }
    private void verifyMonth() {
        if (txtMonth.getText().isBlank() || txtMonth.getText().isBlank()) {
            setMonth("NULL");
        } else {
            setMonth(txtMonth.getText());
        }
    }

    private void verifyYear() {
        if (!txtYear.getText().isBlank() && !txtYear.getText().isBlank()) {
                setYear(Integer.parseInt(txtYear.getText()));
                currentReportWindow.generateReport(indexReport, month, year);
        } else {
            errorMessage.showMessage("ERROR", "El campo de año es requerido.");
        }
    }
    private void txtYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyTyped
        char car = evt.getKeyChar();
        if (car < '0' || car > '9')
            evt.consume();
    }//GEN-LAST:event_txtYearKeyTyped

    public void setData(ReportCardModel data){
        lblReportCardHeader.setText(data.getTitle());
        lblIcon.setIcon(data.getIcon());
        txtMonth.setEnabled(data.isMonth());
        txtYear.setEnabled(data.isYear());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.trojasviejas.swing.buttons.Button btnRInvoice;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblIcon;
    public javax.swing.JLabel lblReportCardHeader;
    private com.trojasviejas.swing.panels.PanelShadow panelShadow1;
    public com.trojasviejas.swing.fields.LinearTextField txtMonth;
    public com.trojasviejas.swing.fields.LinearTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
